[[pages]]
path = "smartrx_web/smartrx.py"
name = "Welcome to SmartRx!!!"
icon = "🏥"

[[pages]]
path = "smartrx_web/news.py"
name = "Daily News"
icon = "🌏"

[[pages]]
path = "smartrx_web/check_ddi.py"
name = "Drug-Drug Interaction Check"
icon = "💊"

[[pages]]
path = "smartrx_web/check_dfi.py"
name = "Drug-Food Interaction Check"
icon = "🍲"

[[pages]]
path = "smartrx_web/drug_list.py"
name = "Drug List"
icon = "📜"

[[pages]]
path = "smartrx_web/about.py"
name = "About"
icon = "ℹ️"

[[pages]]
path = "smartrx_web/contact.py"
name = "Contact"
icon = "📧"